name: ubuntu cross-lfs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: |
        pushd scripts
        bash setup.sh
        popd

    - uses: actions/upload-artifact@v2
      with:
        name: lfs-pi
        path: README.md