name: ubuntu cross-lfs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: |
        sudo apt-get install build-essential libgtk-3-dev
        URL=https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-20.04
        python -m pip install --upgrade pip
        pip install -U -f $URL wxPython
        pip install pyinstaller

    - uses: actions/upload-artifact@v2
      with:
        name: lfs-pi
        path: README.md